config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
     has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :find_book, only: [:show, :edit, :update, :destroy]
    def index 
        @books =Book.all.order("created_at DESC")
    end
    def show
       @book = Book.find(params[:id])
    end
    def new
       @book = current_user.books.build
       @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    def create
       @book = current_user.books.build(book_params)
       @book.category_id = params[:category_id]

        if @book.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    def update
         @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end
    def destroy
        @book.destroy
        redirect_to root_path
    end
    private
    def book_params
        params.require(:book).permit(:title, :description, :author,:category_id)
    end
    def find_book
        @book = Book.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.input :title, label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book </h1>
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= f.select :category_id, @categories %>
	<%= f.input :title, label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <h1><%= link_to  book.title, book_path(book) %></h1>
   <h2><%=  book.description %></h2>
     <h2><%=  book.author %></h2>
<% end %>
<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<h1>New  Books </h1>

<%= render 'form' %>

app/views/books/show.html.erb
 <h2><%=  @book.title %></h2>
   <h3><%=@book.author %></h3>
   <h4>Category : <%=@book.category.name %></h4>
   <p><%= @book.description %></p>
    <%= link_to "Back",  root_path %>
     <% if user_signed_in? %>
		<% if @book.user_id == current_user.id %>
     <%= link_to "Edit", edit_book_path(@book) %>
     <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sur?"} %>
     <% end %>
	<% end %>	
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CPE4252Bookreview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
	<nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "Book Review", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>

 

			<ul class="nav navbar-nav navbar-right">
 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, books_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>



				<% if user_signed_in? %>
					<li><%= link_to "Add Book", new_book_path %></li>
				<% end %>
				
			</ul>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>	

  </body>
</html>